baseURL: ""
languageCode: en-us
theme: PaperMod
title: Redwan Benmansour


defaultContentLanguage: fr
defaultContentLanguageInSubdir: true


params:
  displayFullLangName: true
  mainSections:
  - projects
  defaultTheme: light
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowDate: true
  author: Redwan Benmansour
  images: ["1739734917588.jpg"]


languages:
  en:
    languageName: 🇬🇧
    weight: 10
    contentDir: content/en
    title: Redwan
    menu:
      main:
        - identifier: accueil
          name: 🏠 Home 
          url: /en/
          weight: 10
        - identifier: about
          name: 🙂 About
          url: /en/about/
          weight: 20
        - identifier: projets
          name: 🔧 Projects
          url: /en/projects/
          weight: 30
    params:
      images: ["1739734917588.jpg"]
      profileMode:
        enabled: true
        title: "Redwan Benmansour" # optional default will be site title
        subtitle: "Student in the first year of the work-study engineering program at Grenoble INP – Ense3"
        imageUrl: "1739734917588.jpg" # optional
        imageTitle: "Redwan Benmansour" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Download resume
            url: "/en/CV_EN_Redwan_BENMANSOUR.pdf"
      DateFormat: "January 2, 2006"
      socialIcons: # optional
        - name: "linkedin"
          url: "https://www.linkedin.com/in/redwan-benmansour-48502117a/"
        - name: "github"
          url: "https://github.com/redwanbnmnsr"
        - name: "email"
          url: "mailto:redwan.benmansour@outlook.com"

  fr:
    languageName: 🇫🇷
    weight: 20
    title: Redwan
    contentDir: content/fr
    menu:
      main:
        - identifier: accueil
          name: 🏠 Accueil 
          url: /fr/
          weight: 10
        - identifier: about
          name: 🙂 À propos
          url: /fr/about/
          weight: 20
        - identifier: projects
          name: 🔧 Projets
          url: /fr/projects/
          weight: 30


    params:
      images: ["1739734917588.jpg"]
      profileMode:
        enabled: true
        title: "Redwan Benmansour" # optional default will be site title
        subtitle: "Étudiant en 1ère année à INP Grenoble - Ense3 en Alternance"
        imageUrl: "1739734917588.jpg" # optional
        imageTitle: "Redwan Benmansour" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
          - name: Télécharger le CV
            url: "/fr/CV_FR_Redwan_BENMANSOUR.pdf"
      DateFormat: "2 January 2006"


      socialIcons: # optional
        - name: "linkedin"
          url: "https://www.linkedin.com/in/redwan-benmansour/"
        - name: "github"
          url: "https://github.com/redwanbnmnsr"
        - name: "email"
          url: "mailto:redwan.benmansour@outlook.com"
